"""
Module: toolboxes.PyShoe.pyshoe_export
Description: 
    Handles the execution of PyShoe zero-velocity update (ZUPT) detectors
    and step timing extraction for biomechanical gait analysis. Includes 
    functions for noise estimation from static trials or dynamic segments.

Dependencies:
    - sys
    - numpy
    - pathlib
    - pandas
    - scipy.io
"""

from __future__ import annotations
import sys
import numpy as np
from pathlib import Path
import pandas as pd
from scipy.io import savemat
from scipy.stats import chi2

PYSHOE_DIR = Path(__file__).resolve().parent
if str(PYSHOE_DIR) not in sys.path:
    sys.path.insert(0, str(PYSHOE_DIR))
from Toolboxes.PyShoe.ins_tools.INS import INS

RIGHT_FOOT_COLS = ['acceleration_RightFoot_x', 'acceleration_RightFoot_y', 'acceleration_RightFoot_z', 'angularVelocity_RightFoot_x', 'angularVelocity_RightFoot_y', 'angularVelocity_RightFoot_z']
LEFT_FOOT_COLS = ['acceleration_LeftFoot_x', 'acceleration_LeftFoot_y', 'acceleration_LeftFoot_z', 'angularVelocity_LeftFoot_x', 'angularVelocity_LeftFoot_y', 'angularVelocity_LeftFoot_z']
TARGET_COLS = ["time"] + RIGHT_FOOT_COLS + LEFT_FOOT_COLS

DETECTORS = ['shoe']

def debounce_events(
    event_times: np.ndarray, 
    min_spacing_ms: float = 800.0
) -> np.ndarray:
    """
    Filters out false-positive events that occur too closely together.

    Once a valid event is registered, all subsequent events within the 
    min_spacing_ms window are ignored.

    Parameters
    ----------
    event_times : np.ndarray
        A 1D array of raw event timestamps.
    min_spacing_ms : float, optional
        The minimum required spacing between valid events in milliseconds. Defaults to 800.0.

    Returns
    -------
    np.ndarray
        A 1D array of debounced event timestamps.
    """
    if len(event_times) < 2:
        return event_times
    valid_indices = [0]
    last_valid_time = event_times[0]
    for i in range(1, len(event_times)):
        if (event_times[i] - last_valid_time) >= min_spacing_ms:
            valid_indices.append(i)
            last_valid_time = event_times[i] 
    return event_times[valid_indices]

def clean_raw_zupt_mask(
    raw_mask: np.ndarray, 
    time: np.ndarray, 
    W: int, 
    min_spacing_ms: float = 600.0, 
    to_fo_delay_ms: float = 150.0
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Extracts edges, applies debouncing, and reconstructs a clean boolean mask and event arrays.

    Parameters
    ----------
    raw_mask : np.ndarray
        The raw boolean zero-velocity mask generated by the detector.
    time : np.ndarray
        The 1D array of timestamps corresponding to the mask.
    W : int
        The window size used in the zero-velocity detector.
    min_spacing_ms : float, optional
        The minimum allowed time between consecutive identical events in milliseconds. Defaults to 600.0.
    to_fo_delay_ms : float, optional
        The delay applied from heel-strike to infer foot-off if needed. Defaults to 150.0.

    Returns
    -------
    tuple[np.ndarray, np.ndarray, np.ndarray]
        A tuple containing:
        - cleaned_mask: The filtered boolean mask.
        - valid_hs: Array of validated heel-strike timestamps.
        - valid_fo: Array of validated foot-off timestamps.
    """
    padded = np.concatenate(([False], raw_mask, [False])).astype(int)
    diff = np.diff(padded)
    
    hs_idx = np.where(diff == 1)[0]
    fo_idx = np.where(diff == -1)[0] + (W - 1)
    fo_idx = np.clip(fo_idx, 0, len(time) - 1)
    
    if raw_mask[0] and len(hs_idx) > 0: 
        hs_idx = hs_idx[1:]
        
    hs_times = time[hs_idx]
    fo_times = time[fo_idx]
    
    hs_times = debounce_events(hs_times, min_spacing_ms)
    fo_times = debounce_events(fo_times, min_spacing_ms)
    
    valid_hs, valid_fo = [], []
    cleaned_mask = np.zeros(len(raw_mask), dtype=bool)
    
    for hs in hs_times:
        future_fos = fo_times[fo_times > hs]
        if len(future_fos) > 0:
            fo = future_fos[0] + to_fo_delay_ms
            valid_hs.append(hs)
            valid_fo.append(fo)
            cleaned_mask[(time >= hs) & (time <= fo)] = True
            
    return cleaned_mask, np.array(valid_hs), np.array(valid_fo)

def estimate_noise_and_calibrate_G_from_midstance(
    imu_data: np.ndarray, 
    fs: float, 
    W: int,
    has_gravity: bool = True,
    window_duration_sec: float = 0.1,
    n_of_std: float = 3.0
) -> tuple[float, float]:
    """
    Estimates the baseline sensor noise by isolating the quietest midstance.

    Calculates a rolling variance of the acceleration magnitude to find the 
    minimum variance window in the provided dynamic IMU data.

    Parameters
    ----------
    imu_data : np.ndarray
        An Nx6 array containing [acc_x, acc_y, acc_z, gyr_x, gyr_y, gyr_z].
    fs : float
        Sampling frequency of the data in Hz.
    window_duration_sec : float, optional
        Duration of the sliding window in seconds. Defaults to 0.1.

    Returns
    -------
    tuple[float, float, float]
        Estimated accelerometer (var_a), gyroscope (var_w) noise variances, and optimal G.
    """
    window_size = max(5, int(fs * window_duration_sec))
    acc = imu_data[:, 0:3]
    gyr = imu_data[:, 3:6]
    acc_mag = np.linalg.norm(acc, axis=1)
    acc_mag_series = pd.Series(acc_mag)
    rolling_var = acc_mag_series.rolling(window=window_size).var()
    quietest_end_idx = rolling_var.idxmin()

    optimal_G = None
    
    if pd.isna(quietest_end_idx):
        var_a = np.mean(np.var(acc, axis=0))
        var_w = np.var(gyr, axis=0)
    else:
        quietest_start_idx = int(quietest_end_idx) - window_size + 1
        static_acc = acc[quietest_start_idx : int(quietest_end_idx) + 1]
        static_gyr = gyr[quietest_start_idx : int(quietest_end_idx) + 1]
        var_a = np.mean(np.var(static_acc, axis=0))
        var_w = np.var(static_gyr, axis=0)
        static_T = compute_LRT_array(imu_data[quietest_start_idx : int(quietest_end_idx) + 1], var_a, var_w, W, has_gravity=has_gravity)

        T_static_mean = np.mean(static_T)
        T_static_std = np.std(static_T)

        optimal_G = T_static_mean + n_of_std * T_static_std 

    return max(var_a, 1e-5), np.maximum(var_w, 1e-5), optimal_G

def estimate_noise_and_calibrate_G_from_static_trial(
    static_df: pd.DataFrame, 
    cols: list[str],
    W: int,
    has_gravity: bool = True,
    n_of_std: float = 3.0
) -> tuple[float, float, float]:
    """
    Estimates baseline sensor noise globally from a dedicated static trial.

    This function calculates the standard deviation across the entirety of 
    the provided static trial DataFrame for both accelerometer and gyroscope 
    channels, rather than dynamically searching for a quiet window.

    Parameters
    ----------
    static_df : pd.DataFrame
        The DataFrame containing the static calibration trial data.
    cols : list[str]
        A list of exactly six string column names (3 for acceleration, 3 for gyroscope) 
        to extract from the dataframe.

    Returns
    -------
    tuple[float, float, float]
        Estimated accelerometer (var_a), gyroscope (var_w) noise variances, and optimal G.
    """
    data = static_df[cols].to_numpy()
    acc = data[:, 0:3]
    gyr = data[:, 3:6]
    
    var_a = np.mean(np.var(acc, axis=0))
    var_w = np.var(gyr, axis=0)

    # Extract T values for static segment.
    T = compute_LRT_array(data, var_a, var_w, W, has_gravity)

    T_static_mean = np.mean(T)
    T_static_std = np.std(T)

    optimal_G = T_static_mean + n_of_std * T_static_std 
    
    return max(var_a, 1e-5), np.maximum(var_w, 1e-5), optimal_G

def calibrate_G_from_chi2(
    fs: float, 
    has_gravity: bool = True
) -> float:
    """
    Derives the optimal zero-velocity threshold (G) using a purely static data segment.

    This function uses the chi-squared distribution to compute a threshold that is statistically
    significant above the noise floor, providing a 1% safety margin.

    Parameters
    ----------
    fs : float
        The sampling frequency of the IMU data in Hz.
    has_gravity : bool, optional
        Indicates whether the input IMU data includes static gravity. Defaults to True.

    Returns
    -------
    float
        The optimized threshold value (G) for P(FA)=0.01.
    """
    p_false_alarm = 0.01
    W = max(2, int(fs * 0.04))
    
    # Effective Degrees of Freedom (EDOF)
    dof = 5 if has_gravity else 6
    
    optimal_G = chi2.ppf(1 - p_false_alarm, df=dof)
    
    # Scale the threshold to align with the T statistic division by W
    return optimal_G / W

def compute_shoe_timing(
    imu_data: np.ndarray, 
    var_a: float, 
    var_w: float, 
    W: int, 
    G: float, 
    has_gravity: bool = True
) -> tuple[np.ndarray, np.ndarray]:
    """
    Computes a sample-by-sample zero-velocity boolean array.

    Uses a vectorized implementation of the SHOE likelihood ratio test to flag 
    stationary periods, optimized for high temporal resolution in timing detection.

    Parameters
    ----------
    imu_data : np.ndarray
        An Nx6 array containing [acc_x, acc_y, acc_z, gyr_x, gyr_y, gyr_z].
    var_a : float
        Accelerometer noise variance.
    var_w : float
        Gyroscope noise variance.
    W : int
        Window size in samples.
    G : float
        Statistical threshold for the likelihood ratio test.
    has_gravity : bool, optional
        Whether input data contains static gravity. Defaults to True.

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        A tuple containing:
        - zv: A boolean array (size N) where True indicates stationarity.
        - T_padded: The continuous likelihood ratio test statistic array.
    """
    N = imu_data.shape[0]

    T = compute_LRT_array(imu_data, var_a, var_w, W, has_gravity)

    zv = np.zeros(N, dtype=bool)
    zv[:len(T)] = T < G
    zv[len(T):] = T[-1] < G
    
    T_padded = np.zeros(N)
    T_padded[:len(T)] = T
    T_padded[len(T):] = T[-1]
    
    return zv, T_padded

def compute_LRT_array(
    imu_data: np.ndarray, 
    var_a: float, 
    var_w: float, 
    W: int, 
    has_gravity: bool = True
) -> np.ndarray:
    '''
    Computes the likelihood ratio test (LRT) statistic array for the SHOE detector.
    
    Parameters
    ----------
    imu_data : np.ndarray
        An Nx6 array containing [acc_x, acc_y, acc_z, gyr_x, gyr_y, gyr_z].
    var_a : float
        Accelerometer noise variance.
    var_w : float
        Gyroscope noise variance.
    W : int
        Window size in samples.
    has_gravity : bool, optional
        Whether input data contains static gravity. Defaults to True.

    Returns
    -------
    np.ndarray
        The likelihood ratio test (LRT) statistic array.
    '''
    acc = imu_data[:, 0:3]
    gyro = imu_data[:, 3:6]
    
    inv_a = 1.0 / var_a
    inv_w = 1.0 / var_w

    # Apply independent variance weights before summing
    gyro_sq_mag = np.sum(gyro**2 * inv_w, axis=1)
    window = np.ones(W)
    gyro_term = np.convolve(gyro_sq_mag, window, mode='valid')
    
    if has_gravity:
        acc_sq_mag = np.sum(acc**2, axis=1)
        sum_acc_sq = np.convolve(acc_sq_mag, window, mode='valid')
        sum_acc_x = np.convolve(acc[:, 0], window, mode='valid')
        sum_acc_y = np.convolve(acc[:, 1], window, mode='valid')
        sum_acc_z = np.convolve(acc[:, 2], window, mode='valid')
        sum_acc_mag = np.sqrt(sum_acc_x**2 + sum_acc_y**2 + sum_acc_z**2)
        g = 9.8029
        # Scalar inv_a allows the gravity factoring to function correctly
        acc_term = (sum_acc_sq - 2 * g * sum_acc_mag + W * (g**2)) * inv_a
    else:
        acc_sq_mag = np.sum(acc**2, axis=1)
        acc_term = np.convolve(acc_sq_mag, window, mode='valid') * inv_a
        
    T = (acc_term + gyro_term) / W

    return T

def pyshoe_process_single_file(
    segment: pd.DataFrame, 
    course: str, 
    id: str, 
    clip_id: int,
    true_hs_r: pd.DataFrame | np.ndarray, 
    true_fo_r: pd.DataFrame | np.ndarray, 
    true_hs_l: pd.DataFrame | np.ndarray, 
    true_fo_l: pd.DataFrame | np.ndarray, 
    output_path: Path,
    fs: float,
    has_gravity: bool,
    min_spacing_ms: float = 600.0,
    to_fo_delay_ms: float = 150.0,
    n_of_std: float = 3.0,
    static_df: pd.DataFrame = None
) -> str:
    """
    Processes a single trial dataset across zero-velocity update (ZUPT) detectors.

    Extracts IMU data for left and right feet, applies the specified state detectors, 
    computes bilateral heel strike and foot off events, and exports MATLAB summaries. 
    Optionally uses a static dataframe for global noise estimation.

    Parameters
    ----------
    segment : pd.DataFrame
        The pre-sliced Pandas DataFrame containing the target time frame.
    course : str
        The name of the course or environment directory.
    id : str
        The subject identifier string.
    clip_id : int
        The specific trial or clip number index.
    true_hs_r : pd.DataFrame | np.ndarray
        The ground truth heel strike annotations for the right foot.
    true_fo_r : pd.DataFrame | np.ndarray
        The ground truth foot off annotations for the right foot.
    true_hs_l : pd.DataFrame | np.ndarray
        The ground truth heel strike annotations for the left foot.
    true_fo_l : pd.DataFrame | np.ndarray
        The ground truth foot off annotations for the left foot.
    output_path : pathlib.Path
        Path object pointing to the output directory.
    fs : float
        The sampling frequency of the IMU data in Hz.
    has_gravity : bool
        Indicates if static gravity is present in the accelerometer data.
    static_df : pd.DataFrame, optional
        An optional DataFrame containing a static trial for noise baseline calibration. Defaults to None.

    Returns
    -------
    str
        A status summary string confirming processing success or describing an error.
        
    Raises
    ------
    Exception
        If any error occurs during processing or file export.
    """
    detectors_to_run = []
    for detector_name in DETECTORS:
        out_file = output_path / f"{detector_name}_{min_spacing_ms}_{to_fo_delay_ms}_{n_of_std}" / f'{id}_{course}_{clip_id}.mat'
        if static_df is not None:
            out_file = output_path / f"{detector_name}_static" / f'{id}_{course}_{clip_id}.mat'
        if not out_file.exists():
            detectors_to_run.append((detector_name, out_file))
            
    if not detectors_to_run:
        return f"Skipped {id}_{course} (Already completely processed)"

    try:
        imu_left = segment[LEFT_FOOT_COLS].to_numpy() 
        imu_right = segment[RIGHT_FOOT_COLS].to_numpy() 
        time = segment["time"].to_numpy().squeeze()
        W = max(2, int(fs * 0.04))

        if static_df is not None:
            # 1. Get global static noise
            sigma_a_l, sigma_w_l, calibrated_G_l = estimate_noise_and_calibrate_G_from_static_trial(static_df, LEFT_FOOT_COLS, W=W, has_gravity=has_gravity, n_of_std=n_of_std)
            sigma_a_r, sigma_w_r, calibrated_G_r = estimate_noise_and_calibrate_G_from_static_trial(static_df, RIGHT_FOOT_COLS, W=W, has_gravity=has_gravity, n_of_std=n_of_std)

        else:
            # Fallback to dynamic midstance estimation
            sigma_a_l, sigma_w_l, calibrated_G_l = estimate_noise_and_calibrate_G_from_midstance(imu_left, fs, W=W, has_gravity=has_gravity, n_of_std=n_of_std)
            sigma_a_r, sigma_w_r, calibrated_G_r = estimate_noise_and_calibrate_G_from_midstance(imu_right, fs, W=W, has_gravity=has_gravity, n_of_std=n_of_std)

        for detector_name, out_file in detectors_to_run:
            # Override dictionary G if static calibration was successfully executed for SHOE
            G_val_l = calibrated_G_l
            G_val_r = calibrated_G_r
            
            if detector_name == 'shoe':
                steps_left, T_l = compute_shoe_timing(imu_left, sigma_a_l, sigma_w_l, W, G_val_l, has_gravity)
                steps_right, T_r = compute_shoe_timing(imu_right, sigma_a_r, sigma_w_r, W, G_val_r, has_gravity)
            else:
                T_l, T_r = [], []

                ins_l = INS(imu_left, False, sigma_a=sigma_a_l, sigma_w=sigma_w_l, T=1.0/fs)
                steps_left = ins_l.Localizer.compute_zv_lrt(W=W, G=G_val_l, detector=detector_name)
                
                ins_r = INS(imu_right, False, sigma_a=sigma_a_r, sigma_w=sigma_w_r, T=1.0/fs)
                steps_right = ins_r.Localizer.compute_zv_lrt(W=W, G=G_val_r, detector=detector_name)

            # ... [Rest of the extraction, tagging, and saving logic remains exactly the same] ...

            _, HS_times_left, FO_times_left = clean_raw_zupt_mask(steps_left, time, W, min_spacing_ms=min_spacing_ms, to_fo_delay_ms=to_fo_delay_ms)
            _, HS_times_right, FO_times_right = clean_raw_zupt_mask(steps_right, time, W, min_spacing_ms=min_spacing_ms, to_fo_delay_ms=to_fo_delay_ms)

            def tag_foot(times, label):
                if len(times) == 0: return np.empty((0, 2))
                return np.column_stack((times, np.full(len(times), label)))

            pred_hs_r = tag_foot(HS_times_right, 0)
            pred_hs_l = tag_foot(HS_times_left, 1)
            pred_fo_r = tag_foot(FO_times_right, 0)
            pred_fo_l = tag_foot(FO_times_left, 1)

            y_HS_pred = np.vstack((pred_hs_r, pred_hs_l)) if len(pred_hs_r) or len(pred_hs_l) else np.empty((0, 2))
            y_FO_pred = np.vstack((pred_fo_r, pred_fo_l)) if len(pred_fo_r) or len(pred_fo_l) else np.empty((0, 2))
            
            if len(y_HS_pred): y_HS_pred = y_HS_pred[y_HS_pred[:, 0].argsort()]
            if len(y_FO_pred): y_FO_pred = y_FO_pred[y_FO_pred[:, 0].argsort()]

            true_hs_r_tagged = tag_foot(true_hs_r, 0)
            true_hs_l_tagged = tag_foot(true_hs_l, 1)
            true_fo_r_tagged = tag_foot(true_fo_r, 0)
            true_fo_l_tagged = tag_foot(true_fo_l, 1)

            y_HS_true = np.vstack((true_hs_r_tagged, true_hs_l_tagged)) if len(true_hs_r_tagged) or len(true_hs_l_tagged) else np.empty((0, 2))
            y_FO_true = np.vstack((true_fo_r_tagged, true_fo_l_tagged)) if len(true_fo_r_tagged) or len(true_fo_l_tagged) else np.empty((0, 2))

            if len(y_HS_true): y_HS_true = y_HS_true[y_HS_true[:, 0].argsort()]
            if len(y_FO_true): y_FO_true = y_FO_true[y_FO_true[:, 0].argsort()]

            acc_mag_l = np.linalg.norm(imu_left[:, 0:3], axis=1)
            acc_mag_r = np.linalg.norm(imu_right[:, 0:3], axis=1)

            results = {
                'time': time,
                'acc_mag_l': acc_mag_l,
                'acc_mag_r': acc_mag_r,
                'y_HS': y_HS_true,
                'y_FO': y_FO_true,
                'y_hat_HS': y_HS_pred,     
                'y_hat_FO': y_FO_pred,
                'T_l': T_l if detector_name == 'shoe' else [], 
                'T_r': T_r if detector_name == 'shoe' else [],
                'g_opt': calibrated_G_l if detector_name == 'shoe' else None,
            }      
            out_file.parent.mkdir(parents=True, exist_ok=True)
            savemat(out_file, {'results': results})

        return f"{id}_{course}_{clip_id}.mat Success"
        
    except Exception as e:
        return f"Error on {id}_{course}_{clip_id}: {str(e)}"